# -*- coding: utf-8 -*-
"""Student_Data.csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XG3j3EyI-c3hJQ3ZQA2C3ECJL_g78Pq0
"""

name,math,science,english
Aman,85,78,90
Riya,92,88,95
Rahul,70,75,80
Sneha,88,90,85