# -*- coding: utf-8 -*-
"""student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178Ktdp7PEhjNKCTvdoNJ5uBH7_Z9qqx3
"""

import streamlit as st
import pandas as pd

st.title("Student Performance")

df = pd.read_csv("student_data.csv")

df["average"] = (df["math"] + df["science"] + df["english"]) / 3

st.write(df)

top = df.sort_values("average", ascending=False).iloc[0]

st.write("Top Student")
st.write(top)